### ISSUE TITLE
London 

### ISSUE THREAD

**Issue by Danyal4667** [near/wallet-selector#1103]
**Describe the bug**

**Steps To Reproduce**å

_Steps to reproduce the behavior:_

_Error description_

**Expected behavior**

**Screenshots**

**Desktop**: 
* OS : 
* Browser : 
* Browser Version : 

**Smartphone**: 
* Device : 
* OS <1-- e.g. iOS8.1 -->: 
* Browser : 
* Browser Version : 

**Additional Context**

```[tasklist]
### Tasks
- [ ] https://github.com/near/wallet-selector/pull/1101
- [ ] https://github.com/near/wallet-selector/pull/1102
- [ ] https://github.com/near/wallet-selector/pull/1099
```

**Comment by trechriron** [comment]
@Danyal4667  - what is this for?
