### ISSUE TITLE
[Defect] 

### ISSUE THREAD

**Issue by Emadalshamery** [near/wallet-selector#1232]
**Describe the bug**

**Steps To Reproduce**å

_Steps to reproduce the behavior:_

_Error description_

**Expected behavior**

**Screenshots**

**Desktop**: 
* OS : 
* Browser : 
* Browser Version : 

**Smartphone**: 
* Device : 
* OS <1-- e.g. iOS8.1 -->: 
* Browser : 
* Browser Version : 

**Additional Context**

```[tasklist]
### Tasks
- [ ] https://github.com/near/wallet-selector/pull/1230
- [ ] https://github.com/near/wallet-selector/pull/1231
- [ ] https://github.com/near/wallet-selector/pull/1229
- [ ] https://github.com/near/wallet-selector/pull/1213
- [ ] https://github.com/near/wallet-selector/pull/1227
- [ ] https://github.com/near/wallet-selector/pull/1221
- [ ] https://github.com/near/wallet-selector/pull/1168
- [ ] https://github.com/near/wallet-selector/pull/1228
- [ ] https://github.com/near/wallet-selector/issues/1223
```

```[tasklist]
### Tasks
- [ ] https://github.com/near/wallet-selector/pull/1221
- [ ] https://github.com/near/wallet-selector/pull/1230
- [ ] https://github.com/near/wallet-selector/pull/1229
- [ ] https://github.com/near/wallet-selector/pull/1168
- [ ] https://github.com/near/wallet-selector/pull/1231
- [ ] https://github.com/near/wallet-selector/pull/1213
- [ ] https://github.com/near/wallet-selector/pull/1228
- [ ] https://github.com/near/wallet-selector/pull/1227
- [ ] https://github.com/near/wallet-selector/pull/1226
- [ ] https://github.com/near/wallet-selector/pull/1225
- [ ] https://github.com/near/wallet-selector/issues/1222
- [ ] https://github.com/near/wallet-selector/issues/1224
- [ ] https://github.com/near/wallet-selector/pull/1208
- [ ] https://github.com/near/wallet-selector/issues/1223
```
